plugins:
  - rubocop-erb

inherit_mode:
  merge:
    - Include
    - Exclude

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Include:
    - "**/*.erb"
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "bin/**/*"
